const seedGroups = [
  { id: 'grp_core', name: '核心用户', members: ['u_anna', 'u_ben'] },
  { id: 'grp_vip', name: 'VIP', members: ['u_chen'] },
  { id: 'grp_trial', name: '试用客户', members: [] },
];
const users = [
  { id: 'u_anna', name: 'Anna Zhang', email: 'anna@example.com' },
  { id: 'u_ben', name: 'Ben Liu', email: 'ben@example.com' },
  { id: 'u_chen', name: '陈默', email: 'chen@example.com' },
  { id: 'u_daisy', name: 'Daisy Wang', email: 'daisy@example.com' },
  { id: 'u_eric', name: 'Eric Hu', email: 'eric@example.com' },
];
const state = { role: localStorage.getItem('group-role') || 'manager', selectedId: null, groups: loadGroups(), loading: false, failed: new URLSearchParams(location.search).get('fail') === '1' };
const app = document.querySelector('#app');
const modalRoot = document.querySelector('#modalRoot');
const toast = document.querySelector('#toast');
document.querySelector('#roleSelect').value = state.role;
document.querySelector('#roleSelect').addEventListener('change', (event) => { state.role = event.target.value; localStorage.setItem('group-role', state.role); state.selectedId = null; render(); });

function loadGroups() { try { const parsed = JSON.parse(localStorage.getItem('groups-data')); return Array.isArray(parsed) && parsed.every((group) => group && typeof group.id === 'string' && typeof group.name === 'string' && Array.isArray(group.members)) ? parsed : structuredClone(seedGroups); } catch { return structuredClone(seedGroups); } }
function persist(previous) { try { localStorage.setItem('groups-data', JSON.stringify(state.groups)); return true; } catch { if (previous) state.groups = previous; showToast('保存失败，当前状态未改变，请重试'); render(); return false; } }
function canView() { return state.role !== 'none'; }
function canManage() { return state.role === 'manager'; }
function esc(value) { return String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 2600); }
function initials(name) { return name.split(/\s+/).map((part) => part[0]).slice(0, 2).join('').toUpperCase(); }
function render() {
  if (!canView()) { app.innerHTML = `<section class="forbidden"><div class="empty-icon">!</div><h2>暂无访问权限</h2><p>你没有查看用户分组的权限。请联系组织管理员申请访问。</p></section>`; return; }
  if (state.selectedId) return renderDetail();
  if (state.failed) { app.innerHTML = '<div class="notice">分组列表加载失败，请重试。<button class="link-button" id="retryLoad">重新加载</button></div>'; document.querySelector('#retryLoad').addEventListener('click', () => { state.failed = false; state.groups = loadGroups(); render(); }); return; }
  app.innerHTML = `<div class="page-head"><div><div class="eyebrow">Directory / Groups</div><h1>用户分组</h1><p class="subtitle">集中管理组织用户，快速确认成员归属与规模。</p></div>${canManage() ? '<button class="primary" id="createGroup">＋ 创建分组</button>' : ''}</div>${state.groups.length ? `<div class="grid">${state.groups.map(groupCard).join('')}</div>` : `<section class="empty"><div class="empty-icon">＋</div><h2>还没有分组</h2><p>${canManage() ? '创建第一个分组，开始组织你的用户。' : '当前组织还没有可查看的分组。'}</p>${canManage() ? '<button class="primary" id="createGroupEmpty">创建分组</button>' : ''}</section>`}`;
  document.querySelector('#createGroup')?.addEventListener('click', openCreateModal); document.querySelector('#createGroupEmpty')?.addEventListener('click', openCreateModal); document.querySelector('#retryLoad')?.addEventListener('click', () => { state.failed = false; render(); });
  document.querySelectorAll('[data-group]').forEach((button) => button.addEventListener('click', () => { state.selectedId = button.dataset.group; render(); }));
}
function groupCard(group) { return `<article class="group-card"><div><h2>${esc(group.name)}</h2><span class="count">${group.members.length} 位成员</span></div><div class="card-foot"><span class="detail-meta">ID ${esc(group.id)}</span><button class="link-button" data-group="${esc(group.id)}">查看成员 →</button></div></article>`; }
function renderDetail() {
  const group = state.groups.find((item) => item.id === state.selectedId); if (!group) { state.selectedId = null; render(); return; }
  const memberRows = group.members.map((id) => { const user = users.find((item) => item.id === id); return user ? `<li class="member-row"><div class="member-info"><span class="member-avatar">${initials(user.name)}</span><div><div class="member-name">${esc(user.name)}</div><div class="member-email">${esc(user.email)}</div></div></div>${canManage() ? `<button class="danger" data-remove="${esc(user.id)}">移出</button>` : ''}</li>` : ''; }).join('');
  app.innerHTML = `<div class="detail-head"><button class="back" id="back">← 返回分组</button><span class="detail-meta">/</span><h1 class="detail-title">${esc(group.name)}</h1></div><div class="panel-head" style="padding-left:0;padding-right:0;border-bottom:0"><div><div class="eyebrow">Group members</div><p class="subtitle">${group.members.length} 位成员 · ${esc(group.id)}</p></div>${canManage() ? '<div class="panel-tools"><button class="secondary" id="addMembers">＋ 加入成员</button><button class="primary" id="simulateError">模拟失败</button></div>' : ''}</div><section class="members-panel">${group.members.length ? `<ul class="member-list">${memberRows}</ul>` : `<div class="empty"><div class="empty-icon">◌</div><h2>暂无成员</h2><p>${canManage() ? '从组织用户目录中选择成员加入此分组。' : '该分组目前还没有成员。'}</p>${canManage() ? '<button class="primary" id="addMembersEmpty">加入成员</button>' : ''}</div>`}</section>`;
  document.querySelector('#back').addEventListener('click', () => { state.selectedId = null; render(); }); document.querySelector('#addMembers')?.addEventListener('click', openMemberModal); document.querySelector('#addMembersEmpty')?.addEventListener('click', openMemberModal); document.querySelector('#simulateError')?.addEventListener('click', () => { showToast('成员服务暂时不可用，请稍后重试'); }); document.querySelectorAll('[data-remove]').forEach((button) => button.addEventListener('click', () => removeMember(button.dataset.remove)));
}
function openCreateModal() { modalRoot.innerHTML = `<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="createTitle"><h2 id="createTitle">创建分组</h2><p>分组名称会去除首尾空格，并在组织内按大小写不敏感规则校验唯一性。</p><label class="field">分组名称<input id="groupName" maxlength="80" autofocus placeholder="例如：核心用户" /></label><div id="nameError" class="field-error"></div><div class="modal-actions"><button class="secondary" id="cancelModal">取消</button><button class="primary" id="saveGroup">创建分组</button></div></div></div>`; document.querySelector('#cancelModal').addEventListener('click', closeModal); document.querySelector('#saveGroup').addEventListener('click', createGroup); document.querySelector('#groupName').addEventListener('keydown', (event) => { if (event.key === 'Enter') createGroup(); }); }
function createGroup() { const input = document.querySelector('#groupName'); const name = input.value.trim(); const error = document.querySelector('#nameError'); if (!name) { error.textContent = '请输入分组名称'; return; } if ([...name].length > 50) { error.textContent = '分组名称不能超过 50 个字符'; return; } const previous = structuredClone(state.groups); const latest = loadGroups(); if (latest.some((group) => group.name.toLocaleLowerCase() === name.toLocaleLowerCase())) { error.textContent = '该组织已存在同名分组，请修改名称'; return; } state.groups = latest; state.groups.push({ id: `grp_${Date.now()}`, name, members: [] }); if (!persist(previous)) return; closeModal(); render(); showToast('分组创建成功'); }
function openMemberModal() { const group = state.groups.find((item) => item.id === state.selectedId); const available = users.filter((user) => !group.members.includes(user.id)); modalRoot.innerHTML = `<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true"><h2>加入成员</h2><p>从组织用户目录选择成员加入“${esc(group.name)}”。已在组内的成员可重复提交，系统会按幂等操作处理。</p><label class="field">搜索用户<input id="memberSearch" placeholder="输入姓名或邮箱" /></label><div id="memberChoices" class="check-list">${memberChoices(group, '')}</div><div class="modal-actions"><button class="secondary" id="cancelModal">取消</button><button class="primary" id="confirmMembers">确认加入</button></div></div></div>`; document.querySelector('#cancelModal').addEventListener('click', closeModal); document.querySelector('#memberSearch').addEventListener('input', (event) => { document.querySelector('#memberChoices').innerHTML = memberChoices(group, event.target.value); }); document.querySelector('#confirmMembers').addEventListener('click', () => { const selected = [...modalRoot.querySelectorAll('input[type="checkbox"]:checked')].map((input) => input.value); if (!selected.length) { closeModal(); showToast('未选择成员，当前状态未改变'); return; } const previous = structuredClone(state.groups); const newMembers = selected.filter((id) => !group.members.includes(id)); const existingCount = selected.length - newMembers.length; group.members = [...new Set([...group.members, ...newMembers])]; if (!persist(previous)) return; closeModal(); render(); showToast(existingCount && newMembers.length ? `已加入 ${newMembers.length} 位成员，${existingCount} 位成员已在组内` : existingCount ? '成员已在分组中' : `已加入 ${newMembers.length} 位成员`); }); }
function memberChoices(group, query) { const normalized = query.trim().toLocaleLowerCase(); const matches = users.filter((user) => !normalized || `${user.name} ${user.email}`.toLocaleLowerCase().includes(normalized)); return matches.length ? matches.map((user) => `<label class="check-item"><input type="checkbox" value="${esc(user.id)}" /> <span>${esc(user.name)} <small>${group.members.includes(user.id) ? '（已在组内）' : ''}</small></span></label>`).join('') : '<div class="check-item">没有匹配的组织用户</div>'; }
function removeMember(id) { const group = state.groups.find((item) => item.id === state.selectedId); if (!group.members.includes(id)) { showToast('成员已不在分组中'); return; } const previous = structuredClone(state.groups); group.members = group.members.filter((memberId) => memberId !== id); if (!persist(previous)) return; render(); showToast('成员已移出分组'); }
function closeModal() { modalRoot.innerHTML = ''; }
render();
